title: <p align="center"> Suraksha G Bharadwaj </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/suraksha-g-bharadwaj-b61ab298/">LinkedIn</a> 
  <a href="https://github.com/sgrbharadwaj">GitHub</a>

theme: jekyll-theme-minimal
